-- ==============================================================================
-- QCFI ROURKELA: SUPABASE DATABASE SCHEMA & INITIAL DATA SEED
-- Run this script in the Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS public.hero_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_path TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    event_date TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    main_image_path TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.event_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    image_path TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.quality_concepts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.concept_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_id BIGINT REFERENCES public.quality_concepts(id) ON DELETE CASCADE,
    image_path TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.magazines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    pdf_path TEXT NOT NULL,
    cover_path TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Setup Storage Bucket for Media & Uploads
INSERT INTO storage.buckets (id, name, public) 
VALUES ('media', 'media', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 3. Setup Row Level Security (RLS) & Policies
ALTER TABLE public.hero_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quality_concepts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.concept_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.magazines ENABLE ROW LEVEL SECURITY;

-- Drop any existing policies to allow clean re-runs
DROP POLICY IF EXISTS "Public Read hero_images" ON public.hero_images;
DROP POLICY IF EXISTS "Public Write hero_images" ON public.hero_images;
CREATE POLICY "Public Read hero_images" ON public.hero_images FOR SELECT USING (true);
CREATE POLICY "Public Write hero_images" ON public.hero_images FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Read events" ON public.events;
DROP POLICY IF EXISTS "Public Write events" ON public.events;
CREATE POLICY "Public Read events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Public Write events" ON public.events FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Read event_images" ON public.event_images;
DROP POLICY IF EXISTS "Public Write event_images" ON public.event_images;
CREATE POLICY "Public Read event_images" ON public.event_images FOR SELECT USING (true);
CREATE POLICY "Public Write event_images" ON public.event_images FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Read quality_concepts" ON public.quality_concepts;
DROP POLICY IF EXISTS "Public Write quality_concepts" ON public.quality_concepts;
CREATE POLICY "Public Read quality_concepts" ON public.quality_concepts FOR SELECT USING (true);
CREATE POLICY "Public Write quality_concepts" ON public.quality_concepts FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Read concept_images" ON public.concept_images;
DROP POLICY IF EXISTS "Public Write concept_images" ON public.concept_images;
CREATE POLICY "Public Read concept_images" ON public.concept_images FOR SELECT USING (true);
CREATE POLICY "Public Write concept_images" ON public.concept_images FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Read quizzes" ON public.quizzes;
DROP POLICY IF EXISTS "Public Write quizzes" ON public.quizzes;
CREATE POLICY "Public Read quizzes" ON public.quizzes FOR SELECT USING (true);
CREATE POLICY "Public Write quizzes" ON public.quizzes FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Read magazines" ON public.magazines;
DROP POLICY IF EXISTS "Public Write magazines" ON public.magazines;
CREATE POLICY "Public Read magazines" ON public.magazines FOR SELECT USING (true);
CREATE POLICY "Public Write magazines" ON public.magazines FOR ALL USING (true);

-- Storage bucket RLS policies
DROP POLICY IF EXISTS "Public Read Media" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Media" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Media" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Media" ON storage.objects;

CREATE POLICY "Public Read Media" ON storage.objects FOR SELECT USING (bucket_id = 'media');
CREATE POLICY "Public Insert Media" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'media');
CREATE POLICY "Public Update Media" ON storage.objects FOR UPDATE USING (bucket_id = 'media');
CREATE POLICY "Public Delete Media" ON storage.objects FOR DELETE USING (bucket_id = 'media');

-- 4. Seed Data from SQLite Database
INSERT INTO public.hero_images (id, image_path) VALUES
(2, 'uploads/hero_images/HERO_1.jpeg'),
(3, 'uploads/hero_images/HERO_2.jpeg'),
(4, 'uploads/hero_images/HERO_3.jpeg'),
(5, 'uploads/hero_images/HERO_4.jpeg'),
(6, 'uploads/hero_images/HERO_5.jpeg'),
(7, 'uploads/hero_images/HERO_6.jpeg'),
(8, 'uploads/hero_images/HERO_7.jpeg'),
(9, 'uploads/hero_images/HERO_8.jpeg'),
(10, 'uploads/hero_images/HERO_9.jpeg'),
(11, 'uploads/hero_images/HERO_10.jpeg'),
(12, 'uploads/hero_images/HERO_11.jpeg'),
(13, 'uploads/hero_images/HERO_12.jpeg'),
(14, 'uploads/hero_images/HERO_13.jpeg'),
(15, 'uploads/hero_images/HERO_14.jpeg')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.events (id, name, event_date, title, description, main_image_path) VALUES
(3, 'sss', '2026-09-16', 'sss', 'scasas', 'uploads/event_images/VEG_THALI.jpeg'),
(4, 'ffdW', '2026-12-22', 'cascsa', 'sacsac', 'uploads/event_images/Sentinel_Edge_Logo.png')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.event_images (id, event_id, image_path) VALUES
(3, 3, 'uploads/event_images/Untitled_design_2_page-0001.jpg'),
(4, 4, 'uploads/event_images/opex_logo_2.png')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.quality_concepts (id, title, description) VALUES
(6, 'Learn 5S', '5S — KEY STEPS FOR INDUSTRIES

1. SORT
   • Identify what is necessary and what is unnecessary.
   • Remove obsolete, damaged, duplicate or unused items.
   • Keep only what is required for the work.
   • Dispose of or control unwanted items through approved procedures.

2. SET IN ORDER
   • Give every required item a clearly defined location.
   • Arrange tools, materials and documents according to frequency and sequence of use.
   • Use labels, markings, storage locations and visual controls.
   • Make required items easy to find, use and return.

3. SHINE
   • Clean the workplace, equipment and work areas regularly.
   • Treat cleaning as an inspection activity, not only housekeeping.
   • Identify leaks, damage, abnormalities and unsafe conditions.
   • Correct or report problems through the appropriate system.

4. STANDARDIZE
   • Establish simple and documented workplace standards.
   • Define responsibilities, cleaning schedules and inspection routines.
   • Use checklists, visual standards and standard work instructions.
   • Ensure employees follow the same agreed process.

5. SUSTAIN
   • Make 5S part of everyday work—not a one-time activity.
   • Conduct periodic inspections and internal 5S audits.
   • Track observations, corrective actions and improvement opportunities.
   • Involve workers and supervisors in continuous improvement.
   • Review standards whenever processes, equipment or risks change.

6. SAFETY & COMPLIANCE
   • Identify workplace hazards and implement appropriate controls.
   • Keep emergency exits, fire equipment, electrical panels and safety equipment accessible.
   • Follow applicable occupational-health-and-safety laws, regulations and organizational procedures.
   • Provide appropriate training, competence and personal protective equipment where required.
   • Maintain records and evidence required by applicable systems and regulations.

7. CONTINUOUS IMPROVEMENT
   • Do not stop after achieving a clean and organized workplace.
   • Identify recurring problems and eliminate their root causes.
   • Encourage employee suggestions and corrective actions.
   • Measure performance and continuously improve workplace standards.

CORE PRINCIPLE:
“Right item. Right place. Right condition. Right standard. Every day.”'),

(7, 'Learn LEAN QC', 'LEAN PRINCIPLES — KEY STEPS

1. DEFINE VALUE
   • Understand what the customer actually needs.
   • Identify what creates value from the customer’s perspective.
   • Eliminate activities that do not contribute to that value.

2. MAP THE VALUE STREAM
   • Map the complete process from beginning to end.
   • Identify every step involved in delivering the product or service.
   • Detect waste, delays, bottlenecks and unnecessary movement.
   • Focus improvement efforts on the areas creating the greatest waste.

3. CREATE FLOW
   • Ensure work moves smoothly through the process.
   • Reduce interruptions, waiting time and bottlenecks.
   • Balance processes according to actual demand.
   • Maintain a consistent and efficient workflow.

4. ESTABLISH PULL
   • Produce or deliver based on actual customer demand.
   • Avoid unnecessary production, inventory and resource use.
   • Supply materials and services when they are required.
   • Use demand-driven systems wherever practical.

5. PURSUE PERFECTION
   • Continuously identify and eliminate waste.
   • Encourage employees to suggest improvements.
   • Measure performance and review results regularly.
   • Standardize successful improvements.
   • Treat continuous improvement as an ongoing process.

CORE PRINCIPLE:
“Create maximum customer value with minimum waste through continuous improvement.”'),

(8, 'Learn 6 SIGMA', 'SIX SIGMA — KEY STEPS

1. DEFINE
   • Clearly define the problem, customer requirements and project objectives.
   • Establish the scope, expected outcomes and measurable goals.
   • Ensure the project addresses a genuine business or process need.

2. MEASURE
   • Establish reliable measures for current process performance.
   • Collect relevant and accurate data.
   • Determine the current baseline and identify performance gaps.
   • Verify that measurement methods are consistent and appropriate.

3. ANALYZE
   • Examine the collected data to understand process performance.
   • Identify patterns, variations and potential causes of problems.
   • Use appropriate analytical methods to determine root causes.
   • Validate important findings with objective evidence.

4. IMPROVE
   • Develop solutions that address verified root causes.
   • Test improvements before full implementation where appropriate.
   • Evaluate the effect of changes using measurable results.
   • Implement effective solutions in a controlled manner.

5. CONTROL
   • Establish controls to maintain the improved process.
   • Standardize successful methods and document requirements.
   • Monitor key performance indicators and process variation.
   • Respond promptly when performance moves outside defined limits.
   • Continue reviewing the process for further improvement.

CORE PRINCIPLE:
“Use data and structured problem-solving to reduce variation, improve performance and deliver consistent value.”'),

(9, 'Learn KAIZEN', 'KAIZEN — KEY PRINCIPLES

1. IDENTIFY OPPORTUNITIES
   • Observe the workplace and identify areas that can be improved.
   • Focus on problems, inefficiencies, delays and recurring issues.
   • Use facts and observations rather than assumptions.

2. INVOLVE PEOPLE
   • Encourage employees at every level to contribute ideas.
   • Create an environment where improvement suggestions are welcomed.
   • Use the knowledge and experience of people closest to the process.

3. IMPROVE IN SMALL STEPS
   • Prefer practical, incremental improvements where appropriate.
   • Test changes before wider implementation.
   • Avoid unnecessary complexity when a simple improvement can solve the problem.

4. ELIMINATE WASTE
   • Identify unnecessary activities, waiting, movement, defects and resource usage.
   • Reduce activities that do not create value.
   • Improve the use of time, materials, equipment and human effort.

5. STANDARDIZE IMPROVEMENTS
   • Document successful improvements.
   • Update standard work, procedures and visual controls.
   • Ensure the improved method is consistently followed.

6. CHECK THE RESULTS
   • Measure whether the improvement achieved its intended result.
   • Compare performance before and after the change.
   • Use evidence to determine whether further action is required.

7. CONTINUE THE CYCLE
   • Treat improvement as an ongoing activity.
   • Regularly review processes and identify new opportunities.
   • Build continuous improvement into everyday work.

CORE PRINCIPLE:
“Small, consistent improvements—made by everyone, every day—create lasting progress.”'),

(11, 'NEW TOOLS', 'NEW TOOLS — KEY AREAS

1. DATA ANALYSIS
   • Convert process data into meaningful information.
   • Identify trends, patterns and performance gaps.
   • Use evidence to support improvement decisions.

2. PROCESS MAPPING
   • Visualize the complete workflow from start to finish.
   • Identify unnecessary steps, delays and bottlenecks.
   • Simplify processes wherever practical.

3. VISUAL MANAGEMENT
   • Make important information easy to see and understand.
   • Use charts, boards, indicators, labels and visual controls.
   • Monitor performance and abnormalities at a glance.

4. PROBLEM SOLVING
   • Define problems clearly before taking corrective action.
   • Identify and verify the underlying causes.
   • Implement practical solutions and evaluate their results.

5. TEAM COLLABORATION
   • Involve people who understand the process.
   • Encourage ideas, observations and improvement suggestions.
   • Build shared ownership of improvement activities.

6. ROOT CAUSE ANALYSIS
   • Look beyond symptoms to identify the actual cause.
   • Use structured methods and objective evidence.
   • Prevent recurrence by addressing verified root causes.

CORE PRINCIPLE:
“Use the right tools, involve the right people, and turn problems into measurable improvements.”'),

(12, 'Learn TQM', 'TQM — TOTAL QUALITY MANAGEMENT

1. FOCUS ON THE CUSTOMER
   • Understand customer needs, expectations and requirements.
   • Deliver products and services that consistently meet those requirements.
   • Use customer feedback to identify opportunities for improvement.

2. CONTINUOUS IMPROVEMENT
   • Regularly identify opportunities to improve processes and performance.
   • Reduce waste, variation, defects and unnecessary activities.
   • Encourage small, consistent improvements across the organization.

3. QUALITY IMPROVEMENT
   • Build quality into every process rather than relying only on final inspection.
   • Prevent defects and address problems at their source.
   • Maintain consistent standards across products, services and operations.

4. ACCURATE EVALUATION
   • Measure performance using reliable and relevant data.
   • Review results against defined objectives and standards.
   • Use evidence to identify gaps and guide improvement actions.

5. INVOLVE ALL EMPLOYEES
   • Encourage employees at every level to participate in quality improvement.
   • Value ideas, knowledge and experience from people closest to the work.
   • Build shared responsibility for quality and organizational performance.

CORE PRINCIPLE:
“Quality is everyone’s responsibility—built into every process, measured with evidence, and improved continuously.”'),

(13, 'Learn QC', 'LEARN QC — QUALITY CONTROL FUNDAMENTALS

1. UNDERSTAND QUALITY
   • Know the required specifications, standards and acceptance criteria.
   • Understand what “conforming” and “non-conforming” mean.
   • Focus on preventing defects, not only detecting them.

2. INSPECT & MEASURE
   • Check materials, components and products against defined requirements.
   • Use appropriate and calibrated measuring instruments.
   • Record measurements accurately and consistently.

3. IDENTIFY DEFECTS
   • Detect deviations from specifications as early as possible.
   • Classify defects according to their type, severity and impact.
   • Prevent non-conforming products from moving to the next stage.

4. ANALYZE THE CAUSE
   • Investigate why the defect occurred.
   • Use data and structured problem-solving methods.
   • Distinguish the root cause from the visible symptom.

5. TAKE CORRECTIVE ACTION
   • Correct identified problems through controlled actions.
   • Address the cause to prevent recurrence.
   • Verify whether the corrective action is effective.

6. STANDARDIZE & DOCUMENT
   • Maintain inspection procedures, specifications and records.
   • Follow approved work instructions and quality standards.
   • Keep traceable evidence of inspections and corrective actions.

7. PREVENT RECURRENCE
   • Monitor process performance continuously.
   • Identify recurring defects and improvement opportunities.
   • Strengthen controls where necessary.

CORE PRINCIPLE:
“Measure accurately. Detect early. Correct the cause. Prevent recurrence.”'),

(14, 'Learn SQC', 'LEARN SQC — STATISTICAL QUALITY CONTROL

1. UNDERSTAND VARIATION
   • Learn why processes naturally vary.
   • Distinguish normal variation from unusual variation.
   • Understand how variation affects quality and consistency.

2. COLLECT QUALITY DATA
   • Collect accurate and relevant process data.
   • Use consistent measurement methods.
   • Ensure data is reliable before making decisions.

3. ANALYZE THE DATA
   • Use statistical methods to understand process behavior.
   • Identify patterns, trends and unusual observations.
   • Convert data into meaningful quality information.

4. USE CONTROL CHARTS
   • Monitor process performance over time.
   • Identify signals that may indicate special causes.
   • Take action when the process shows significant changes.

5. CONTROL PROCESS PERFORMANCE
   • Maintain processes within defined requirements and control limits.
   • Investigate abnormal variation promptly.
   • Use appropriate corrective and preventive actions.

6. IMPROVE WITH EVIDENCE
   • Use statistical evidence to guide improvement decisions.
   • Reduce unnecessary variation and defects.
   • Verify whether improvements produce sustained results.

CORE PRINCIPLE:
“Use reliable data and statistical thinking to understand variation, control processes and improve quality.”')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.concept_images (id, concept_id, image_path) VALUES
(6, 6, 'uploads/concept_images/LEARN_5S.png'),
(7, 7, 'uploads/concept_images/LEARN_LEAN_QC.png'),
(8, 8, 'uploads/concept_images/LEARN_6_SIGMA.png'),
(9, 9, 'uploads/concept_images/Learn_Kaizen.png'),
(11, 11, 'uploads/concept_images/NEW_TOOLS.png'),
(12, 12, 'uploads/concept_images/Learn_TQM.png'),
(13, 13, 'uploads/concept_images/LEARN_QC.png'),
(14, 14, 'uploads/concept_images/LEARN_SQC.png')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.quizzes (id, question, option_a, option_b, option_c, option_d, correct_option) VALUES
(1, 'GVSDV', 'E', 'EE', 'EEE', 'EEEE', 'C')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.magazines (id, title, pdf_path, cover_path) VALUES
(2, 'Kaleidoscope e-magazine Published by QCFI Rourkela chapter', 'uploads/magazines/KaleidoscopeFY25-26_Q4_issue.pdf', 'uploads/covers/magazine_cover_image_1.png'),
(3, 'Kaleidoscope(FY26-27) Q1 issue', 'uploads/magazines/KaleidoscopeFY26-27_Q1_issue.pdf', 'uploads/covers/magazine_cover_image_2.png')
ON CONFLICT (id) DO NOTHING;

-- Reset sequence IDs so future inserts increment properly
SELECT setval(pg_get_serial_sequence('public.hero_images', 'id'), COALESCE(MAX(id), 1)) FROM public.hero_images;
SELECT setval(pg_get_serial_sequence('public.events', 'id'), COALESCE(MAX(id), 1)) FROM public.events;
SELECT setval(pg_get_serial_sequence('public.event_images', 'id'), COALESCE(MAX(id), 1)) FROM public.event_images;
SELECT setval(pg_get_serial_sequence('public.quality_concepts', 'id'), COALESCE(MAX(id), 1)) FROM public.quality_concepts;
SELECT setval(pg_get_serial_sequence('public.concept_images', 'id'), COALESCE(MAX(id), 1)) FROM public.concept_images;
SELECT setval(pg_get_serial_sequence('public.quizzes', 'id'), COALESCE(MAX(id), 1)) FROM public.quizzes;
SELECT setval(pg_get_serial_sequence('public.magazines', 'id'), COALESCE(MAX(id), 1)) FROM public.magazines;
